#!/bin/bash

alias bfg='java -jar ~/.userfiles/bfg.jar'
alias g='git'
alias gpl='git pull'
alias gpu='git push'
alias gaa='git add -A'
alias ga='git add'
alias gc='git checkout'
alias cb='cd ..'
alias cd..='cd ..'
alias jjar='java -jar'
#alias build=". ./build"
#alias run=". ./run"
alias a='atom .'
alias open='xdg-open'
alias tarc='tar -czvf'
alias tarx='tar -xzvf'
alias resource='source ~/.bashrc'
alias chcur='stat -c "%a %n"'

alias volup='pactl set-sink-volume @DEFAULT_SINK@ +25%'
alias voldown='pactl set-sink-volume @DEFAULT_SINK@ -25%'
alias setvol='pactl set-sink-volume @DEFAULT_SINK@'
alias vol-up='volup'
alias vol-down='voldown'
alias set-vol='setvol'
alias volume='setvol'
alias volset='setvol'
alias vol-set='setvol'
alias gradlew='./gradlew'
alias gradleci='gradle build --continuous'
alias hrm='\rm -rf'

alias cr='crystal'

alias leak-test='valgrind --leak-check=full --show-leak-kinds=all'
