#!/bin/bash

alias cp='rsync -ah --no-i-r --info=progress2'
alias bfg='java -jar ~/.userfiles/bin/bfg.jar'
alias g='git'
alias gpl='git pull'
alias gpu='git push'
alias gaa='git add -A'
alias ga='git add'
alias gc='git checkout'
alias gprune='git fetch --all --prune'
alias cb='cd ..'
alias cd..='cd ..'
alias jjar='java -jar'
#alias build=". ./build"
#alias run=". ./run"
alias a='atom .'
alias vm='vagrant'
alias vmp='vagrant up'
alias vms='vagrant ssh'
alias vmh='vagrant halt'
alias vmd='vagrant destroy'
alias open='xdg-open'
alias tarc='tar -czvf'
alias tarx='tar -xzvf'
alias resource='source ~/.bashrc'
alias chcur='stat -c "%a %n"'

alias light='xbacklight ='
alias blight='xbacklight'
alias lightup='xbacklight + 10'
alias lightdown='xbacklight - 10'
alias light-up='lightup'
alias light-down='lightdown'

alias gradlew='./gradlew'
alias gradleci='gradle build --continuous'
alias hrm='\rm -rf'

alias xclip='xclip -selection c'

alias texclean='rm -i *.aux *.fls *.dvi *.blg *.fdb_latexmk *.log *.out *.toc *.lof *.bbl'

alias suspend='systemctl suspend'

alias gr='gradle'
alias cr='crystal'
alias po='poetry'

alias docker-rmall='docker rm $(docker ps -a -q); docker rmi $(docker images -q)'

alias leak-test='valgrind --leak-check=full --show-leak-kinds=all'
