#!/bin/bash
source "$USERFILES/addons/complete-alias/complete_alias"

# work-around to enable tab-completing for sudo correctly
alias sudo='sudo'
complete -F _complete_alias sudo

# aliases
complete -F _complete_alias cp
complete -F _complete_alias g
complete -F _complete_alias jjar
complete -F _complete_alias vm
complete -F _complete_alias open
complete -F _complete_alias tarc
complete -F _complete_alias tarx
complete -F _complete_alias gr
complete -F _complete_alias cr
complete -F _complete_alias po
complete -F _complete_alias leak-test


# FIXME: causing issues with stalling on remote login
#if type pipenv &> /dev/null; then
#    eval "$(_PIPENV_COMPLETE=bash_source pipenv)"
#fi

if type pipx &> /dev/null; then
    eval "$(register-python-argcomplete pipx)"
fi
